name: Python CI

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Docker build and push TEST
        if: github.ref != 'refs/heads/master' && !contains(github.ref, 'renovate/')
        run : |
          docker build -t dashmockserver .
          docker tag dashmockserver arnaudf93/dashmockserver:${GITHUB_REF#refs/*/}
          docker push arnaudf93/dashmockserver:${GITHUB_REF#refs/*/}

      - name: Docker build and push DEV
        if: github.ref == 'refs/heads/master'
        run : |
          docker build -t dashmockserver .
          docker tag dashmockserver arnaudf93/dashmockserver:latest
          docker push arnaudf93/dashmockserver:latest
