name: Python CI

on: ["push"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set Docker tag for release
        run: |
          echo "DOCKER_TAG_NAME=latest" >> $GITHUB_ENV
    #    if: github.ref == 'refs/heads/master'

      - name: Set Docker tag for test
        run: |
          echo "DOCKER_TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/master' && !contains(github.ref, 'renovate/')

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
    #    if: success() && !contains(github.ref, 'renovate/')
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{env.DOCKER_TAG_NAME}}
          file: ./Dockerfile